### ISSUE TITLE
✏️ [ FEAT REQ ] Add to F-Droid

### ISSUE THREAD

**Issue by inson1** [octoshrimpy/quik#32]
I know that you want to do that, I'm just add it here, so there si issue for it :)
Please share what is missing and what did you already did :)

**Comment by octoshrimpy** [comment]
I need to figure out github auto-signing, as well as obtanium not pulling latest apk from releases. With the drama and uncertainty over f-droid right now, I'm going to focus on obtanium first, and then once that's figured out I will move to f-droid (if it's still around). thank you for the issue and reminder!

**Comment by octoshrimpy** [comment]
for comments and explanations: 
https://news.ycombinator.com/item?id=38517576

for the actual info:
https://gist.github.com/obfusk/ec0628d1d6b6c70468079de415ad1e2d
https://gitlab.com/fdroid/admin/-/issues/447

**Comment by octoshrimpy** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14515

this is now in the works!

**Comment by licaon-kter** [comment]
can you @octoshrimpy add  `images/icon.png` and maybe `phoneScreenshots/...` to https://github.com/octoshrimpy/quik/tree/master/metadata/en-US ?

**Comment by inson1** [comment]
also decription could be better - why write about obtanium and releases on github in F-droid description?

+https://github.com/octoshrimpy/quik/issues/56

**Comment by octoshrimpy** [comment]
> can you @octoshrimpy add `images/icon.png` and maybe `phoneScreenshots/...` to https://github.com/octoshrimpy/quik/tree/master/metadata/en-US ?

I can. working on a new icon, that's why it's missing atm, but should be there soon. :)


> /close this :)

_panik_ it's on f-droid eeeeeeeeeee!


> why write about obtanium and releases on github in F-droid description?

because this is my first time submitting to f droid, and it was 1am at the time, and I just copy pasted from github description :sweat_smile: 

> btw link this issue with metadata pr

I'm not sure what you mean. could you explain a bit more?

**Comment by licaon-kter** [comment]
It's not setup to pickup non-stable automatically, no.

**Comment by DJCrashdummy** [comment]
ohhh... that's why it seems (for people not visiting the github repo) that there is not much going on.

IMHO the only issues which really need to be fixed to have a stable release with solid basic SMS functions are #179 and #117.
...other features like archiving messages, blocking numbers, scheduled SMS, group messages, backups etc. are just additional features which don't block the basic usage of the app.
and for some features there are even other FOSS apps available which do a better job because it's their whole purpose, like [SMS Import / Export](https://github.com/tmo1/sms-ie).

**Comment by octoshrimpy** [comment]
> I think I'm satisfied with the current stable version. I don't use much SMS other than receiving tele spam messages. Everyone uses WhatsApp or signal these days.

you're gonna love that #60 got addressed, then. I'll be working today on seeing what I can do to get a pre-release out for yall that hunger for ~~breaking changes~~ new things to test. :D

**Comment by DJCrashdummy** [comment]
> Everyone uses WhatsApp or signal these days.

@veganomy if **everyone** would use solely messenger services via internet, there wouldn't be any carrier providing SMS anymore. and i'm pretty sure you can't speak for the whole world (neither do i)! - the only thing i can say is that in my country there is a good amount of people relying an SMS as they can't/won't be always online.

**Comment by DJCrashdummy** [comment]
just in case you didn't know @octoshrimpy: since this issue is about fdroid releases and if there may be too much breaking changes... the recommended release by fdroid doesn't have to be the latest. as far as i know it can be at least set to be N releases behind the latest or even static to a specific version.
apps which use the feature permanently are - from the top of my head - [*K-9 Mail*](https://f-droid.org/packages/com.fsck.k9/) and [*OsmAnd*](https://f-droid.org/packages/net.osmand.plus/).

**Comment by licaon-kter** [comment]
> Everyone uses WhatsApp or signal these days.

and how do you login exactly? Oh, SMS....

**Comment by licaon-kter** [comment]
@veganomy the issues with SMS are well known, I guess we're beyond that

**Comment by octoshrimpy** [comment]
@veganomy 
> SMS lacks encryption

_👀 looks around in stegcloak handshake and PGP ideas_


---

as far as f-droid, @DJCrashdummy i'm not sure I follow what you mean. I understand the f-droid release doesn't have to be github latest, but the sentence after that confused me.

**Comment by licaon-kter** [comment]
old https://f-droid.org/packages/org.smssecure.smssecure/

new https://f-droid.org/packages/com.afkanerd.deku/

etc

**Comment by DJCrashdummy** [comment]
> as far as f-droid, @DJCrashdummy i'm not sure I follow what you mean. I understand the f-droid release doesn't have to be github latest, but the sentence after that confused me.

@octoshrimpy i meant, if you are afraid of too much breaking changes it may be worth to release some betas or RC (even on fdroid - to get easier resp. more testers), but not mark them as the "suggested" version (to avoid a ton of drama because of automatic updates).
maybe also RegEx can be used to automatically mark the latest stable release as "suggested" by fdroid. but i'm not sure anymore... unfortunately i haven't contributed to fdroid for quite some time now. 😦

**Comment by DJCrashdummy** [comment]
> SMS [...] relies on your telecom credits [...]

well... so does mobile data. depending on your plan you may not get charged extra for the one or the other if you have flat rates. but they are not available everywhere in the world.

> SMS [...] it's too slow.

@veganomy i'm not sure what that should mean... as both go through some servers until it is delivered to you. i'm also not really sure how this should/could be measured to conclude a universal answer about the whole system, instead of baseless advertisement claims.
...and if you are not always online (maybe because you don't have unlimited data and get charged extra for it) - thus just using your phone mainly as a phone - the messages of an internet-based messenger only arrive when you decide to go online. ...so hardly a push function at all.

> The reason is Security. SMS lacks encryption, [...] Your service provider can easily read your messages. If that's okay to you, then sure. No one's stopping you to use SMS as your default messenger.

as licaon-kter said: the issues of SMS are well known...
and i did **not** say that anybody should prefer SMS over an encrypted messengers (although there are apps also mentioned by licaon-kter which encrypt SMS)... it just itches my nerves when someone demands other people to use a walled garden which is spying on its users and selling their data with the stupid justification of *"everybody is using it"*. and this silly argument is only "working" because they are limiting federation on purpose.
-> if you could only call people using the same carrier as you or if you could only send an email to people using the same provider as you, people would be rioting... but when they are pulling this shit with messengers, people are fine with it. i don't get it! 😖 

long story, short: as long as the de-facto-standard for messaging (may it be iMessage, FB messenger, WhatsApp etc. - it differs in different parts of the world) isn't capable of federation, SMS will still be a thing.
e.g. make something like [Matrix](https://matrix.org/) the default messenger system and it would be easier to sunset the old SMS (although the always online issue still persists).

> The only reason to have SMS is to get bank OTP verifications, which are very unsecure too these days.

as long as the thing sent to you unencrypted is just an **additional** token of a MFA - with at least **one other secret** token - and on top of that is just valid for a short period of time, i'm pretty fine with it.
interestingly one of my banks tried to scare me away from using SMS verification and force me to user their app... but guess what: the initial setup has to be done with a 6-figure code sent to you via SMS which is valid until you use it!!! 😱 *"...just for convenience that you can setup your account later at home."* 🤦
this concludes me to the assumption that the real reason has to be something different than security... perhaps it is to get people away from SMS to spare some bucks (in the long run).
and similarly bad as the big security hole is the fact that if you don't use an Android or Apple phone with their app store (and perhaps also a locked bootloader), you are screwed anyways.

> I donno why they [bank] still use mobile verification instead of other secure ways.

well... that's the result of my remarks: as long as companies try to force everybody in their own walled garden, the only free, standardized and federating system which really everybody has by default, will persist as something like "the lowest common denominator". ...no matter how old and insecure it is. 🤷
